Addressing Issue Number 12
fnplus/footsteps-extension pull request #13
Opened 2019-12-03 15:55 UTC by VarthanV

I have solved the Issue number 12 that was opened by fetching the title and the description of the website when the extension is clicked under the guidance of @xlogix

2019-12-03 18:05 UTC, arjunmahishi requested changes
Apart from the comments, get rid of unwanted new lines

2019-12-03 18:05 UTC, arjunmahishi commented on src/content.js
> +  var title = document.querySelector("title").text;
we can just do `document.title` right?

2019-12-03 18:05 UTC, arjunmahishi commented on src/content.js
> +    source: `<h1> ${title} - ${data} </h1>`
we should send this data a json like:
```
{
    "title": " ",
    "description": " ",
    ...
}
```

2019-12-03 18:05 UTC, arjunmahishi commented on src/popup/popup.js
> +    var message = document.getElementById('message');
where is this `message` element?

2019-12-03 18:05 UTC, arjunmahishi commented on src/popup/popup.js
> +      file: "content.js"
is this the only way to inject data into popup?
if so, let's name the script something else. Something more specific and descriptive.

2019-12-03 18:05 UTC, arjunmahishi commented on src/auth/auth.js
> +   }
remove this if this was just a test. let's keep auth.js clean

2019-12-03 18:05 UTC, arjunmahishi commented on src/auth/auth.js
> +    console.log(doc);
same as above

2019-12-04 13:20 UTC, VarthanV commented
I have made the necessary changes  and returned a json object to the main file

2019-12-04 13:22 UTC, VarthanV commented
No Bro what Abhishek bro said is to extract the data and send it to the backend. I am just learning GraphQL the message is nothing but a div in auth.html to make sure that my logic works . Please specify me what  i have to do after extracting the data

2019-12-05 05:51 UTC, arjunmahishi requested changes

2019-12-05 05:51 UTC, arjunmahishi commented on src/popup/popup.js
> +  var message = document.getElementById("message");
This still not addressed. Can you point me to the "message" element?

2019-12-05 05:51 UTC, arjunmahishi commented on src/popup/popup.js
> +      file: "content.js"
Let's rename `content.js` to something like `metadata-fetcher.js` or something similar

2019-12-05 05:52 UTC, arjunmahishi commented
We can merge this once the "message" element is sorted out. (this is assuming the changes are tested and working fine)

2019-12-05 06:04 UTC, VarthanV commented
Content.js is  a convention to name the file otherwise we cannot access the dom elements and get data . I have removed the message div I just used it for debugging the data will be returned as JSON to the popup file. If you want to know whether it works i have logged the title and metadata in the console when the site loads we can disable that after you approve the PR.

2019-12-06 07:59 UTC, arjunmahishi approved these changes

2019-12-06 07:59 UTC, merged

2019-12-06 08:00 UTC, arjunmahishi commented
@VarthanV  Thank you for your contributions!